name: Lint then test
on: pull_request
permissions:
  id-token: write
  contents: read
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: install dependencies
        run: |
          NODE_ENV=build npm install
      - name: lint
        run: |
          npm run lint
      - name: run test suites
        run: |
          npm run test
